<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="java.util.Properties" %>
<%@page import="javax.mail.*" %>
<%!
  private Session ping(String host, String port,
          String user, String password,
          String auth, String starttls) {

    Properties props = new Properties();
    props.setProperty("mail.host", host);
    props.setProperty("mail.user", user);
    props.setProperty("mail.password", password);
    props.setProperty("mail.transport.protocol", "smtp");
    props.setProperty("mail.smtp.port", port);
    props.setProperty("mail.smtp.auth", auth);
    props.setProperty("mail.smtp.starttls.enable", starttls);

    Session mailSession = Session.getInstance(props);
    Transport transport = null;
    try {
      transport = mailSession.getTransport();
      transport.connect(
              mailSession.getProperty("mail.user"),
              mailSession.getProperty("mail.password"));
    } catch (MessagingException ex) {
      log("Failed to ping SMTP server: " + host, ex);
      return null;
    } finally {
      try {
        transport.close();
      } catch (MessagingException ex) {
      }
    }

    return mailSession;
  }
%>
<%
      String from = request.getParameter("from");
      String to = request.getParameter("to");
      String host = request.getParameter("host");
      String port = request.getParameter("port");
      String user = request.getParameter("user");
      String password = request.getParameter("password");
      String auth = "on".equalsIgnoreCase(request.getParameter("auth")) ? "true" : null;
      String starttls = "on".equalsIgnoreCase(request.getParameter("starttls")) ? "true" : null;

      if (host != null && !host.trim().isEmpty()) {
        Session mailSession = ping(host, port, user, password, auth, starttls);
        if (mailSession != null) {
          mailSession.setDebug(true);
          application.setAttribute("mail.session", mailSession);
          application.setAttribute("mail.from", from);
          application.setAttribute("mail.to", to);
          response.sendRedirect(application.getContextPath() + "/index.jsp");
        }
      }
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>JavaMail Pages Tag Library - Examples Application</title>
    <style type="text/css">
      <!--
      div.field{margin:8px auto;width:650px;}
      div.field label{float:left;text-align:right;width:175px;}
      div.field label.checkbox{float:none;text-align:left;width:auto;}
      div.field input{margin-left:5px;width:260px;}
      div.field input.checkbox{margin-left:180px;width:auto;}
      div.field span.hint{display:block;margin-left:180px;width:260px; color:#666666}
      div.field span.error{display:block;margin-left:180px;width:260px; color:#ff0000}

      div.submit{margin:12px auto;width:650px;}
      div.submit input{margin-left:180px;}
      -->
    </style>
  </head>
  <body>
    <h1>JavaMail Pages (JMP) Tag Library</h1>
    <h2>Examples Web Application </h2>
    <p>
      Welcome to the jmp-examples web application! This standalone
      application includes a variety of basic JSP pages that demonstrate
      using JavaMail Pages (JMP) Tag Library.
    </p>
    <p>
      Before exploring the examples, you need config your outgoing mail (SMTP)
      server. Your e-mail address on that server and a recipient address is
      also required. Once you submit the form, these two addresses will be
      saved in servlet context attributes. All e-mail messages generated by
      example pages will use the addresses as "from" and "to" header field
      values.
    </p>
    <div style="margin: 48px auto">
      <form method="post" enctype="application/x-www-form-urlencoded">
        <div class="field">
          <% if (host != null) {%>
          <span class="error">Failed to connect the server. Please verify the information you typed in.</span>
          <% }%>
          <label for="host">SMTP server host:</label>
          <input id="host" name="host" value="${param['host']}"/>
          <span class="hint">Example: smtp.gmail.com</span>
        </div>
        <div class="field">
          <label for="port">SMTP server port number:</label>
          <input id="port" name="port" value="${param['port']}"/>
          <span class="hint">Example: 587</span>
        </div>
        <div class="field">
          <label for="user">E-mail user name:</label>
          <input id="user" name="user" value="${param['user']}"/>
        </div>
        <div class="field">
          <label for="password">Password:</label>
          <input id="password" name="password" type="password" value="${param['password']}"/>
        </div>
        <div class="field">
          <input id="starttls" name="starttls" type="checkbox" class="checkbox" checked="${param['starttls']}"/>
          <label for="starttls" class="checkbox">Use STARTTLS</label>
        </div>
        <div class="field">
          <input id="auth" name="auth" type="checkbox" class="checkbox" checked="${param['auth']}"/>
          <label for="auth" class="checkbox">My Server need authentication</label>
        </div>
        <div class="field">
          <label for="from">Your e-mail address:</label>
          <input id="from" name="from" value="${param['from']}"/>
          <span class="hint">Example: examples@gmail.com</span>
        </div>
        <div class="field">
          <label for="to">Recipient address:</label>
          <input id="to" name="to" value="${param['to']}"/>
          <span class="hint">For demonstration, could be the same with your e-mail address</span>
        </div>
        <div class="submit">
          <input id="submit" name="submit" type="submit" title="Submit" value="Submit"/>
        </div>
      </form>
    </div>
  </body>
</html>
